type UblInvoice = { number: string; issuedAt: Date; dueAt: Date | null; currency: string; counterpartName: string; counterpartSiren: string; counterpartPeppolEndpoint: string | null; counterpartPeppolEndpointScheme: string | null; totalHtCents: number; totalVatCents: number; totalTtcCents: number; lines: Array<{ id: string; label: string; quantity: unknown; unitPriceHtCents: number; totalHtCents: number; vatRateBasisPoints: number }> };
type LegalEntity = { legalName: string; siren: string; vatNumber: string | null; peppolEndpoint: string | null; peppolEndpointScheme: string | null; addressLine1: string | null; postalCode: string | null; city: string | null; countryCode: string };
const xml = (value: unknown) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const amount = (cents: number) => (cents / 100).toFixed(2);
const date = (value: Date) => value.toISOString().slice(0, 10);
const vatExemptionReason = "TVA non applicable, article 293 B du CGI";
const party = (name: string, siren: string, endpoint: string, endpointScheme: string, legal?: LegalEntity, countryCode?: string) => `<cac:Party><cbc:EndpointID schemeID="${xml(endpointScheme)}">${xml(endpoint)}</cbc:EndpointID><cac:PartyIdentification><cbc:ID schemeID="0002">${xml(siren)}</cbc:ID></cac:PartyIdentification><cac:PartyName><cbc:Name>${xml(name)}</cbc:Name></cac:PartyName>${legal ? `<cac:PostalAddress><cbc:StreetName>${xml(legal.addressLine1 || "Non renseignée")}</cbc:StreetName><cbc:CityName>${xml(legal.city || "Non renseignée")}</cbc:CityName><cbc:PostalZone>${xml(legal.postalCode || "00000")}</cbc:PostalZone><cac:Country><cbc:IdentificationCode>${xml(legal.countryCode)}</cbc:IdentificationCode></cac:Country></cac:PostalAddress>` : countryCode ? `<cac:PostalAddress><cac:Country><cbc:IdentificationCode>${xml(countryCode)}</cbc:IdentificationCode></cac:Country></cac:PostalAddress>` : ""}${legal?.vatNumber ? `<cac:PartyTaxScheme><cbc:CompanyID>${xml(legal.vatNumber)}</cbc:CompanyID><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:PartyTaxScheme>` : ""}<cac:PartyLegalEntity><cbc:RegistrationName>${xml(name)}</cbc:RegistrationName><cbc:CompanyID schemeID="0002">${xml(siren)}</cbc:CompanyID></cac:PartyLegalEntity></cac:Party>`;
export function buildUblInvoice(invoice: UblInvoice, seller: LegalEntity) {
  const vatGroups = [...new Set(invoice.lines.map((line) => line.vatRateBasisPoints))];
  const vatBreakdown = vatGroups.map((rate) => { const taxable = invoice.lines.filter((line) => line.vatRateBasisPoints === rate).reduce((sum, line) => sum + line.totalHtCents, 0); const tax = Math.round(taxable * rate / 10000); const exemption = rate === 0 ? `<cbc:TaxExemptionReason>${vatExemptionReason}</cbc:TaxExemptionReason>` : ""; return `<cac:TaxSubtotal><cbc:TaxableAmount currencyID="${xml(invoice.currency)}">${amount(taxable)}</cbc:TaxableAmount><cbc:TaxAmount currencyID="${xml(invoice.currency)}">${amount(tax)}</cbc:TaxAmount><cac:TaxCategory><cbc:ID>${rate ? "S" : "E"}</cbc:ID><cbc:Percent>${(rate / 100).toFixed(2)}</cbc:Percent>${exemption}<cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:TaxCategory></cac:TaxSubtotal>`; }).join("");
  const lines = invoice.lines.map((line, index) => { const exemption = line.vatRateBasisPoints === 0 ? `<cbc:TaxExemptionReason>${vatExemptionReason}</cbc:TaxExemptionReason>` : ""; return `<cac:InvoiceLine><cbc:ID>${index + 1}</cbc:ID><cbc:InvoicedQuantity unitCode="C62">${xml(line.quantity)}</cbc:InvoicedQuantity><cbc:LineExtensionAmount currencyID="${xml(invoice.currency)}">${amount(line.totalHtCents)}</cbc:LineExtensionAmount><cac:Item><cbc:Name>${xml(line.label)}</cbc:Name><cac:ClassifiedTaxCategory><cbc:ID>${line.vatRateBasisPoints ? "S" : "E"}</cbc:ID><cbc:Percent>${(line.vatRateBasisPoints / 100).toFixed(2)}</cbc:Percent>${exemption}<cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:ClassifiedTaxCategory></cac:Item><cac:Price><cbc:PriceAmount currencyID="${xml(invoice.currency)}">${amount(line.unitPriceHtCents)}</cbc:PriceAmount><cbc:BaseQuantity unitCode="C62">1</cbc:BaseQuantity></cac:Price></cac:InvoiceLine>`; }).join("");
  return `<?xml version="1.0" encoding="UTF-8"?><Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"><cbc:CustomizationID>urn:cen.eu:en16931:2017</cbc:CustomizationID><cbc:ProfileID>S1</cbc:ProfileID><cbc:ID>${xml(invoice.number)}</cbc:ID><cbc:IssueDate>${date(invoice.issuedAt)}</cbc:IssueDate>${invoice.dueAt ? `<cbc:DueDate>${date(invoice.dueAt)}</cbc:DueDate>` : ""}<cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode><cbc:DocumentCurrencyCode>${xml(invoice.currency)}</cbc:DocumentCurrencyCode><cac:AccountingSupplierParty>${party(seller.legalName, seller.siren, seller.peppolEndpoint || seller.siren, seller.peppolEndpointScheme || "0002", seller)}</cac:AccountingSupplierParty><cac:AccountingCustomerParty>${party(invoice.counterpartName, invoice.counterpartSiren, invoice.counterpartPeppolEndpoint || invoice.counterpartSiren, invoice.counterpartPeppolEndpointScheme || "0002", undefined, "FR")}</cac:AccountingCustomerParty><cac:TaxTotal><cbc:TaxAmount currencyID="${xml(invoice.currency)}">${amount(invoice.totalVatCents)}</cbc:TaxAmount>${vatBreakdown}</cac:TaxTotal><cac:LegalMonetaryTotal><cbc:LineExtensionAmount currencyID="${xml(invoice.currency)}">${amount(invoice.totalHtCents)}</cbc:LineExtensionAmount><cbc:TaxExclusiveAmount currencyID="${xml(invoice.currency)}">${amount(invoice.totalHtCents)}</cbc:TaxExclusiveAmount><cbc:TaxInclusiveAmount currencyID="${xml(invoice.currency)}">${amount(invoice.totalTtcCents)}</cbc:TaxInclusiveAmount><cbc:PayableAmount currencyID="${xml(invoice.currency)}">${amount(invoice.totalTtcCents)}</cbc:PayableAmount></cac:LegalMonetaryTotal>${lines}</Invoice>`;
}
