import type { RouteDoc } from "./schemas.js";

const groups: Record<string, [string, string][]> = {
  Activité: [
    ["GET /api/activity", "Consulter le fil d'activité et les préférences"],
    ["PUT /api/activity/preferences", "Modifier les préférences du fil d'activité"],
    ["POST /api/activity/mark-read", "Marquer les activités comme lues"],
  ],
  Administration: [
    ["GET /api/admin/logs", "Rechercher les journaux API (administrateur plateforme)"],
    ["GET /api/admin/logs/:id", "Consulter un journal API (administrateur plateforme)"],
    ["GET /api/admin/overview", "Consulter les statistiques de la plateforme"],
    ["PATCH /api/admin/users/:userId/plan", "Modifier l'abonnement d'un utilisateur"],
  ],
  Auth: [
    ["POST /api/auth/login-options", "Obtenir les modes de connexion disponibles pour une adresse email"],
    ["POST /api/auth/register", "Créer un compte avec un jeton d'inscription"],
    ["POST /api/auth/verify-code", "Se connecter avec le code reçu par email"],
    ["POST /api/auth/password/login", "Se connecter avec un mot de passe"],
    ["POST /api/auth/password/setup", "Définir un mot de passe avec un jeton valide"],
  ],
  "Facturation électronique": [
    ["GET /api/workspace/electronic-invoicing", "Consulter la configuration de facturation électronique"],
    ["PUT /api/workspace/electronic-invoicing/legal-entity", "Enregistrer l'identité légale de l'association"],
    ["POST /api/workspace/electronic-invoicing/super-pdp/connect", "Obtenir le lien d'autorisation Super PDP"],
    ["DELETE /api/workspace/electronic-invoicing/super-pdp", "Déconnecter Super PDP"],
    ["POST /api/workspace/electronic-invoicing/super-pdp/callback", "Finaliser la connexion OAuth Super PDP"],
  ],
  Matériel: [
    ["PATCH /api/equipment/:id", "Modifier des cellules du catalogue matériel"],
    ["POST /api/equipment/photo", "Importer une photo de matériel"],
    ["GET /api/workspaces/:workspaceId/equipment", "Consulter le catalogue d'un autre espace autorisé"],
    ["GET /api/equipment/groups", "Lister les groupes de matériel"],
    ["POST /api/equipment/groups", "Créer un groupe de matériel"],
    ["PUT /api/equipment/groups/:id", "Renommer un groupe de matériel"],
    ["DELETE /api/equipment/groups/:id", "Supprimer un groupe de matériel"],
    ["POST /api/equipment/groups/:id/items", "Ajouter un équipement à un groupe"],
    ["PATCH /api/equipment/groups/:id/items/:itemId", "Modifier la quantité d'un équipement dans un groupe"],
    ["DELETE /api/equipment/groups/:id/items/:itemId", "Retirer un équipement d'un groupe"],
    ["POST /api/equipment/import", "Importer des équipements depuis un autre espace"],
    ["POST /api/events/:eventId/equipment/bulk-import", "Ajouter plusieurs équipements du catalogue à un événement"],
    ["POST /api/events/:eventId/equipment/import-preview", "Extraire les lignes d'un document pour préparer un import"],
    ["POST /api/events/:eventId/equipment/import-confirm", "Confirmer les lignes d'un import de matériel"],
    ["POST /api/events/:eventId/equipment/group-import", "Ajouter un groupe de matériel à un événement"],
  ],
  Budget: [
    ["PATCH /api/expenses/:id", "Modifier une seule cellule d'une dépense"],
    ["PATCH /api/incomes/:id", "Modifier une seule cellule d'un revenu"],
  ],
  Notifications: [
    ["GET /api/events/:eventId/notifications", "Consulter les notifications d'un événement"],
    ["PUT /api/events/:eventId/notifications", "Configurer les notifications d'un événement"],
  ],
  Tâches: [
    ["GET /api/events/:eventId/task-categories", "Lister les catégories de tâches"],
    ["POST /api/events/:eventId/task-categories", "Créer une catégorie de tâches"],
    ["PUT /api/events/:eventId/task-categories/:id", "Modifier une catégorie de tâches"],
    ["DELETE /api/events/:eventId/task-categories/:id", "Supprimer une catégorie de tâches"],
    ["POST /api/tasks/:id/comments", "Ajouter un commentaire à une tâche"],
    ["POST /api/tasks/:id/attachments", "Rattacher un fichier à une tâche"],
    ["DELETE /api/tasks/:id/attachments/:attachmentId", "Retirer une pièce jointe d'une tâche"],
  ],
  Fichiers: [
    ["GET /uploads/association-logos/:fileName", "Télécharger un logo d'association"],
    ["POST /api/workspace/logo", "Importer le logo de l'association"],
    ["DELETE /api/workspace/logo", "Supprimer le logo de l'association"],
    ["GET /uploads/equipment-photos/:fileName", "Télécharger une photo de matériel"],
    ["GET /uploads/person-documents/:fileName", "Télécharger un document de contact (session requise)"],
    ["POST /api/uploads/person-documents", "Importer un document de contact"],
    ["GET /uploads/task-attachments/:fileName", "Télécharger une pièce jointe de tâche"],
    ["POST /api/uploads/task-attachments", "Importer une pièce jointe de tâche"],
  ],
  Bénévoles: [
    ["GET /api/public/volunteers/portal/:token", "Consulter son portail bénévole avec un lien privé"],
    ["PATCH /api/public/volunteers/portal/:token/planning", "Accepter ou refuser des créneaux proposés"],
    ["POST /api/public/volunteers/portal/:token/swaps", "Demander un échange de créneaux"],
    ["PATCH /api/public/volunteers/portal/:token/swaps/:id", "Accepter ou refuser un échange"],
    ["GET /api/public/volunteers/:token", "Consulter le formulaire public de candidature"],
    ["POST /api/public/volunteers/:token", "Envoyer une candidature bénévole"],
    ["GET /api/events/:eventId/volunteers", "Consulter les candidatures et le planning bénévole"],
    ["GET /api/events/:eventId/volunteers/contracts", "Lister les conventions de bénévolat d'un événement"],
    ["GET /api/people/:personId/volunteers/contracts", "Lister les conventions de bénévolat d'un contact"],
    ["GET /api/events/:eventId/volunteers/contracts/:id/:format", "Télécharger une convention ou ses preuves depuis l'événement"],
    ["GET /api/people/:personId/volunteers/contracts/:id/:format", "Télécharger une convention ou ses preuves depuis le contact"],
    ["POST /api/events/:eventId/volunteers/contracts", "Créer une convention de bénévolat figée"],
    ["POST /api/events/:eventId/volunteers/contracts/:id/invite", "Envoyer une invitation à signer la convention"],
    ["POST /api/events/:eventId/volunteers/contracts/:id/cancel", "Annuler une demande de signature en attente"],
    ["GET /api/public/volunteers/contracts/:token", "Consulter la convention à signer depuis son lien personnel"],
    ["GET /api/public/volunteers/contracts/:token/:format", "Télécharger sa convention ou son dossier de preuve"],
    ["POST /api/public/volunteers/contracts/:token/code", "Recevoir un code de signature par email"],
    ["POST /api/public/volunteers/contracts/:token/sign", "Signer la convention avec le code reçu par email"],
    ["POST /api/events/:eventId/volunteers/shifts/batch", "Créer plusieurs créneaux identiques"],
    ["POST /api/events/:eventId/volunteers/assignments/preview", "Prévisualiser les affectations automatiques"],
    ["POST /api/events/:eventId/volunteers/assignments/notify", "Envoyer les plannings aux bénévoles par email"],
    ["POST /api/events/:eventId/volunteers/assignments/apply", "Appliquer les affectations du planning"],
    ["POST /api/events/:eventId/volunteers/applications/:id/badge", "Créer ou renouveler le badge d'un bénévole"],
    ["POST /api/events/:eventId/volunteers/check-in", "Enregistrer la présence depuis un badge"],
    ["PUT /api/events/:eventId/volunteers/form", "Configurer le formulaire de candidature"],
    ["POST /api/events/:eventId/volunteers/form/rotate", "Renouveler le lien public de candidature"],
    ["PATCH /api/events/:eventId/volunteers/applications/:id", "Examiner une candidature bénévole"],
    ["PUT /api/events/:eventId/volunteers/services/:id/bookings", "Réserver ou annuler un repas"],
    ["PATCH /api/events/:eventId/volunteers/bookings/:id", "Marquer un repas comme servi ou non servi"],
    ...["shifts", "services"].flatMap((resource): [string, string][] => [
      [`POST /api/events/:eventId/volunteers/${resource}`, `Créer ${resource === "shifts" ? "un créneau bénévole" : "un service de restauration"}`],
      [`PUT /api/events/:eventId/volunteers/${resource}/:id`, `Modifier ${resource === "shifts" ? "un créneau bénévole" : "un service de restauration"}`],
      [`DELETE /api/events/:eventId/volunteers/${resource}/:id`, `Supprimer ${resource === "shifts" ? "un créneau bénévole" : "un service de restauration"}`],
    ]),
  ],
  Finance: [
    ["GET /api/finance/invoices/:id", "Consulter une facture et ses lignes"],
    ["GET /api/finance/invoices/:id/pdf", "Télécharger une facture au format PDF"],
    ["GET /api/finance/overview", "Consulter les factures et notes de frais"],
    ["GET /api/finance/events", "Lister les événements disponibles pour une note de frais"],
    ["GET /api/finance/analytics", "Lister les axes analytiques"],
    ["PUT /api/finance/analytics", "Configurer les axes analytiques"],
    ["GET /api/expense-claims/mine", "Consulter ses propres notes de frais"],
    ["POST /api/expense-claims", "Soumettre une note de frais"],
    ["POST /api/expense-claims/:id/approve", "Approuver une note de frais et créer la dépense"],
    ["POST /api/finance/invoices", "Créer un brouillon de facture"],
    ["PUT /api/finance/invoices/:id", "Modifier un brouillon de facture"],
    ["POST /api/finance/invoices/:id/issue", "Émettre et numéroter définitivement une facture"],
    ["POST /api/finance/invoices/:id/send", "Envoyer une facture par email"],
    ["POST /api/finance/invoices/:id/transmit-super-pdp", "Transmettre une facture à Super PDP"],
  ],
  Personnes: [
    ["PATCH /api/people/:id", "Modifier des cellules d'un contact"],
    ["POST /api/people/:id/documents", "Rattacher un document à un contact"],
    ["DELETE /api/people/documents/:documentId", "Retirer un document d'un contact"],
    ["POST /api/people/:id/history", "Ajouter une note à l'historique d'un contact"],
    ["DELETE /api/people/history/:noteId", "Supprimer une note de l'historique d'un contact"],
  ],
};

export const additionalDocs: Record<string, RouteDoc> = Object.fromEntries(
  Object.entries(groups).flatMap(([tag, entries]) => entries.map(([key, summary]) => [key, { tags: [tag], summary }])),
);
